import React, { useEffect, useState } from 'react';
import { generateWinterContent } from '../services/geminiService';
import { GeneratedContent } from '../types';
import { Sparkles, Image as ImageIcon } from 'lucide-react';

const DemoContent: React.FC = () => {
  const [content, setContent] = useState<GeneratedContent | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchContent = async () => {
      setLoading(true);
      const data = await generateWinterContent();
      setContent(data);
      setLoading(false);
    };
    fetchContent();
  }, []);

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 pt-24 pb-12 px-4 sm:px-6 lg:px-8 relative z-10 transition-colors duration-700">
      
      <div className="max-w-3xl mx-auto space-y-8">
        {/* Mock Search Header */}
        <div className="flex items-center gap-4 border-b pb-4 mb-8">
           <div className="h-8 w-8 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold">G</div>
           <div className="flex-1 h-10 bg-white shadow-sm border rounded-full px-4 flex items-center text-gray-400 text-sm">
             Winter vacation spots 2025...
           </div>
        </div>

        {/* Mock Content Card */}
        <div className="bg-white rounded-xl shadow-lg border border-gray-100 overflow-hidden">
          <div className="h-64 w-full bg-slate-800 relative group overflow-hidden">
             <img 
               src="https://picsum.photos/1200/600?grayscale" 
               alt="Winter Scene" 
               className="w-full h-full object-cover opacity-80 group-hover:scale-105 transition-transform duration-700"
             />
             <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end p-6">
                <h1 className="text-3xl font-bold text-white drop-shadow-md">
                  {loading ? (
                    <span className="animate-pulse bg-white/30 h-8 w-64 block rounded"></span>
                  ) : (
                    content?.headline
                  )}
                </h1>
             </div>
          </div>
          
          <div className="p-8 space-y-4">
            <div className="flex gap-2">
              {loading ? (
                 <>
                   <div className="h-6 w-20 bg-gray-200 rounded-full animate-pulse"></div>
                   <div className="h-6 w-24 bg-gray-200 rounded-full animate-pulse"></div>
                 </>
              ) : (
                content?.tags.map((tag, idx) => (
                  <span key={idx} className="px-3 py-1 bg-blue-50 text-blue-600 text-xs font-medium rounded-full">
                    {tag}
                  </span>
                ))
              )}
            </div>

            <div className="prose prose-lg text-gray-600 leading-relaxed">
              {loading ? (
                 <div className="space-y-3">
                   <div className="h-4 bg-gray-200 rounded w-full animate-pulse"></div>
                   <div className="h-4 bg-gray-200 rounded w-5/6 animate-pulse"></div>
                   <div className="h-4 bg-gray-200 rounded w-4/6 animate-pulse"></div>
                 </div>
              ) : (
                <p>{content?.body}</p>
              )}
            </div>
            
            <div className="pt-6 flex items-center gap-2 text-sm text-gray-400 border-t mt-6">
              <Sparkles size={16} />
              <span>Content generated by Gemini 3 Flash</span>
            </div>
          </div>
        </div>

        {/* Mock Search Results */}
        {[1, 2, 3].map((i) => (
            <div key={i} className="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
               <div className="h-4 w-1/3 bg-gray-200 rounded animate-pulse mb-2"></div>
               <div className="h-3 w-3/4 bg-gray-100 rounded animate-pulse"></div>
            </div>
        ))}

      </div>
    </div>
  );
};

export default DemoContent;
